AnimalesMVC (API)/TiendaAnimales/Models/Animal.cs
using System.ComponentModel.DataAnnotations;

namespace TiendaAnimales.Models
{
    public class Animal
    {
        public int IdAnimal { get; set; }

        [Required(ErrorMessage = "El campo nombre animal es obligatorio.")]
        [Display(Name = "Nombre de animal")]
        [StringLength(50, ErrorMessage = "El nombre de animal introducido no puede exceder los 50 caracteres.")]
        public string NombreAnimal { get; set; }

       
        [StringLength(50, ErrorMessage = "El campo Raza no puede exceder los 50 caracteres.")]
        public string Raza { get; set; }

        [Required(ErrorMessage = "Es obligatorio seleccionar un tipo de animal.")]
        [Display(Name = "Tipo de animal")]
        [Range(1, int.MaxValue, ErrorMessage = "Se debe seleccionar un tipo de animal.")]
        public int RIdTipoAnimal { get; set; }

        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public DateTime? FechaNacimiento { get; set; }
    }
}

AnimalesMVC (API)/TiendaAnimales/Models/ErrorViewModel.cs
namespace TiendaAnimales.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AnimalesMVC (API)/TiendaAnimales/Models/TipoAnimal.cs
namespace AnimalesMVC.Models
{
    public class TipoAnimal
    {
        public int IdTipoAnimal { get; set; }
        public string TipoDescripcion { get; set; }
    }
}

AnimalesMVC (API)/TiendaAnimales/Controllers/AnimalesController.cs
using AnimalesMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;
using TiendaAnimales.Models;

namespace TiendaAnimales.Controllers
{
    public class AnimalesController : Controller
    {
        private readonly HttpClient _client;

        public AnimalesController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri("https://localhost:7275/"); // URL base de la API
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Mensaje = "¡Valor pasado por viewbag!";

            List<Animal> lstAnimals = new List<Animal>();
            
            // Realizar la solicitud GET a la API
            HttpResponseMessage response = await _client.GetAsync("ObtenerTodosLosAnimales");

            if (response.IsSuccessStatusCode)
            {
                lstAnimals = await response.Content.ReadFromJsonAsync<List<Animal>>();
            }
            else
            {
                // Manejar el error si la solicitud no fue exitosa
                // Por ejemplo, mostrar un mensaje de error o manejar el flujo de la aplicación
                ViewBag.Error = "No se pudieron obtener los animales desde la API.";
            }

            HttpResponseMessage responseTipo = await _client.GetAsync("ObtenerTodosLosTiposAnimales");
            var tiposAnimales = await responseTipo.Content.ReadFromJsonAsync<List<TipoAnimal>>();

           
            Random random = new Random();
            int numeroAleatorio = random.Next(1, tiposAnimales.Count); 


            ViewBag.EjemploBlabla = "El " + tiposAnimales[numeroAleatorio].TipoDescripcion + " es tu animal de la suerte!";

            return View(lstAnimals);
        }

        public async Task<IActionResult> Crear()
        {
            await CargarComboTipoAnimal();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Animal nuevoAnimal)
        {
            if (ModelState.IsValid)
            {
                // Serializar el nuevoAnimal a JSON
                string json = JsonConvert.SerializeObject(nuevoAnimal);
                StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

                // Realizar la solicitud POST a la API para insertar el nuevo animal
                HttpResponseMessage response = await _client.PostAsync("InsertarAnimal", content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index"); // Redirigir a la acción "Index" si la inserción fue exitosa
                }
                else
                {
                    // Manejar el error si la solicitud no fue exitosa
                    // Por ejemplo, mostrar un mensaje de error o manejar el flujo de la aplicación
                    ViewBag.Error = "No se pudo insertar el nuevo animal en la API.";
                }
            }
            await CargarComboTipoAnimal();


            return View(nuevoAnimal);
        }        


        private async Task CargarComboTipoAnimal()
        {
            List<TipoAnimal> tiposAnimales =  new List<TipoAnimal>();
            // Realizar la solicitud GET a la API
            HttpResponseMessage response = await _client.GetAsync("ObtenerTodosLosTiposAnimales");

            if (response.IsSuccessStatusCode)
            {
                tiposAnimales = await response.Content.ReadFromJsonAsync<List<TipoAnimal>>(); 
            }
            else
            {
                // Manejar el error si la solicitud no fue exitosa
                // Por ejemplo, mostrar un mensaje de error o manejar el flujo de la aplicación
                ViewBag.Error = "No se pudieron obtener los animales desde la API.";
            }

            // Agregar la opción predeterminada "Seleccionar..."
            tiposAnimales.Insert(0, new TipoAnimal { IdTipoAnimal = 0, TipoDescripcion = "Seleccionar..." });

            ViewBag.TiposAnimales = new SelectList(tiposAnimales, "IdTipoAnimal", "TipoDescripcion");

        }
    }
}

AnimalesMVC (API)/TiendaAnimales/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TiendaAnimales.Models;

namespace TiendaAnimales.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }       

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AnimalesMVC (API)/TiendaAnimales/ViewComponents/InteractivoTiposAnimalesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TiendaAnimales.ViewComponents
{
    public class InteractivoTiposAnimalesViewComponent : ViewComponent
    {
        Dictionary<string, string> tiposAnimal = new Dictionary<string, string>();

        public IViewComponentResult Invoke()
        {
            Dictionary<string, string> tiposAnimal = new Dictionary<string, string>() {   
                {
                    "Peces", "Los peces son animales acuáticos que se mantienen en peceras como mascotas decorativas."
                },
                {
                    "Elefantes", "Los elefantes son mamíferos de gran tamaño con trompas largas y colmillos," +
                    " y a menudo se encuentran en manadas en hábitats salvajes."
                },
                {
                    "Jirafas", "Las jirafas son animales con cuellos largos y patrones únicos en su pelaje, " +
                    "generalmente se encuentran en zonas de sabana."
                },
                {
                    "Leones", "Los leones son grandes felinos que viven en grupos llamados manadas, son depredadores " +
                    "principales y cazan en grupo."
                },
                {
                    "Tigres", "Los tigres son felinos grandes y poderosos que tienen rayas en su pelaje y son animales " +
                    "solitarios que cazan de forma individual."
                },
                {
                    "Osos", "Los osos son mamíferos omnívoros de gran tamaño que viven en diferentes hábitats, desde " +
                    "bosques hasta regiones árticas."
                },
                {
                    "Canguros", "Los canguros son marsupiales que se caracterizan por sus saltos largos y potentes, " +
                    "y a menudo se encuentran en Australia."
                }
            };
            return View(tiposAnimal);
        }
    }
}

AnimalesMVC (API)/TiendaAnimales/Views/Animales/Crear.cshtml
@model Animal
@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<form asp-action="crear" asp-controller="animales" method="post" asp-antiforgery="true">
    <div asp-validation-summary="All" class="text-danger"></div>  

    <div class="form-group mb-2">
        <label asp-for="NombreAnimal"></label>
        <input asp-for="NombreAnimal" class="form-control" />
        <span asp-validation-for="NombreAnimal" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Raza"></label>
        <input asp-for="Raza" class="form-control" />
        
    </div>

    <div class="form-group mb-2">
        <label asp-for="RIdTipoAnimal"></label>
        <select asp-for="RIdTipoAnimal" class="form-select" asp-items="@ViewBag.TiposAnimales"></select>
        <span asp-validation-for="RIdTipoAnimal" class="text-danger"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="FechaNacimiento"></label>
        <input asp-for="FechaNacimiento" class="form-control" type="date" />
        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AnimalesMVC (API)/TiendaAnimales/Views/Animales/Index.cshtml
@model List<Animal>

<ul>
    <h1>@ViewBag.Mensaje</h1>
    
    @foreach (Animal animal in Model)
    {
        <li>Id: @animal.IdAnimal 
            Nombre: @animal.NombreAnimal 
            Raza: @animal.Raza 
            RIdTipoAnimal: @animal.RIdTipoAnimal 
            Fecha de nacimiento:@(animal.FechaNacimiento.HasValue ? animal.FechaNacimiento.Value.ToString("dd/MM/yyyy") : "Sin fecha") 
        </li>       
    }
    <div>
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Error
            </div>
        }
    </div>
    <h1>@ViewBag.EjemploBlabla</h1>
</ul>

AnimalesMVC (API)/TiendaAnimales/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AnimalesMVC (API)/TiendaAnimales/Views/Shared/Components/InteractivoTiposAnimales/Default.cshtml
@model Dictionary<string, string>
@*
    ViewComponent
*@

<style>
    .tipoAnimales {
        border: solid 1px #aaa;
        border-radius: 10px;
        padding: 12px;
    }

        .tipoAnimales .animales {
            display: inline-block;
            float: left;
            max-width: 200px;
            font-size: 12px;
        }

    .clearer {
        clear: both;
    }
</style>

<h2>¡Estoy podría cargarse desde base de datos!</h2>

<div class="tipoAnimales">
    <p>Tipos de animal</p>
    @foreach (var item in Model)
    {
        <div class="animales m-2">
            <h4>@item.Key</h4>
            <p>
                @item.Value
            </p>
        </div>
    }
    
    <div class="clearer"></div>
</div>

AnimalesMVC (API)/TiendaAnimales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TiendaAnimales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TiendaAnimales.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TiendaAnimales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
       @*      @await Html.PartialAsync("_TiposAnimales")
            @await Component.InvokeAsync("InteractivoTiposAnimales") *@
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TiendaAnimales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AnimalesMVC (API)/TiendaAnimales/Views/Shared/_TiposAnimales.cshtml
@*
   Vista parcial tipo animales
*@

<style>
    .tipoAnimales{
        border: solid 1px #aaa;
        border-radius: 10px;
        padding: 12px;
    }
        .tipoAnimales .animales{
            display: inline-block;
            float: left;
            max-width: 200px;
            font-size: 12px;
        }
    .clearer {
        clear: both;
    }
</style>

<div class="tipoAnimales">
    <p>Tipos de animal</p>
    <div class="animales m-2">
        <h4>Gatos</h4>
        <p>
            Los gatos son animales independientes y cariñosos que suelen ser excelentes compañeros.
        </p>
    </div>
    <div class="animales m-2">
        <h4>Perros</h4>
        <p>
            Los perros son mascotas leales y cariñosas que a menudo se consideran parte de la familia.
        </p>
    </div>
    <div class="animales m-2">
        <h4>Conejos</h4>
        <p>
            Los conejos son animales adorables y juguetones que suelen ser excelentes mascotas.
        </p>
    </div>
    <div class="animales m-2">
        <h4>Hamsters</h4>
        <p>
            Los hámsters son pequeños roedores que a menudo se mantienen como mascotas en jaulas.
        </p>
    </div>
    <div class="clearer"></div>
</div>